### ISSUE TITLE
Some questiones about the demo.py

### ISSUE THREAD

**Issue by Jh271441** [ethz-asl/cvae_exploration_planning#3]
I have read your paper and code recently, and was inspired by your extraordinary idea. But I wonder what the demo.py means, because the red arrow(x_new) and orange arrows(x) seem to skip unpredictable. I fonud the orange arrow sometimes skip the wall after only one frame. Can you explain it for me? Thank you very much!

**Comment by Schmluk** [comment]
Hi @Jh142857 

Thank you for your interest and patience! As mentioned [here](https://github.com/ethz-asl/cvae_exploration_planning#using-the-simulator), the orange arrow is the previous robot pose, with red arrow being the newly chosen pose the robot moves to. If the robot is in a local minimum, we will use the global planner to relocate the robot to a new frontier, this should be indicated in the terminal output. The current configuration of the simulator does not show the real-time motion rollout, but the fast simulated version, this is why the robot appears to be teleported for every move.
Hope this helps, let us know if you have further questions!

**Comment by Jh271441** [comment]
Thank you very much for your explaining! @Schmluk
